production:
  password: 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
  theme_id: "118687629504"
  store: mm-header-component.myshopify.com
  ignore_files:
    - config/settings_data.json

development:
  password: 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
  theme_id: "118687858880"
  store: mm-header-component.myshopify.com
  ignore_files:
    - config/settings_data.json
